### ISSUE TITLE
Composer 2.x installation problem

### ISSUE THREAD

**Issue by mwi-gofore** [nunomaduro/phpinsights#445]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | 1.14.0

Could you tag a new version, so that this package is installable by Composer 2.x:

```
# composer update nunomaduro/phpinsights
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires nunomaduro/phpinsights v1.14.0 -> satisfiable by nunomaduro/phpinsights[v1.14.0].
    - nunomaduro/phpinsights v1.14.0 requires composer/composer ^1.7 -> found composer/composer[1.7.0-RC, ..., 1.10.x-dev] but the package is fixed to 2.0.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
```

Using `dev-master` version works just fine...

<!--
Love PHP Insights? Please consider supporting us via Patreon or OpenCollective:
👉  https://www.patreon.com/nunomaduro
👉  https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=66BYDWAT92N6L
--

**Comment by axelitus** [comment]
Hopefully a new release can be tagged soon.

**Comment by olivernybroe** [comment]
The new release won't be made before we have fixed #431, #436, #446. 

Help on these would be highly appreciated.

**Comment by Braunson** [comment]
This is still an issue, curious why this hasn't been resolved?

I'm using Composer 2.0.12 and getting the same error:

```
PS : composer require nunomaduro/phpinsights --dev
Using version ^1.14 for nunomaduro/phpinsights
./composer.json has been updated
Running composer update nunomaduro/phpinsights
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - nunomaduro/phpinsights[v1.14.0, ..., v1.x-dev] require composer/composer ^1.7 -> found composer/composer[1.7.0-RC, ..., 1.10.x-dev] but the package is fixed to 2.0.11 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires nunomaduro/phpinsights ^1.14 -> satisfiable by nunomaduro/phpinsights[v1.14.0, v1.14.1, v1.x-dev].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

**Comment by 50bhan** [comment]
@Braunson As @olivernybroe said before, we need to fix a couple of issues before fixing this. The main problem is deprecated dependencies that are still in progress.
