### ISSUE TITLE
Doesn't run when installed globally

### ISSUE THREAD

**Issue by francislavoie** [nunomaduro/phpinsights#48]
I tried to install it globally using `composer global require nunomaduro/phpinsights` because I have dependency conflicts in my project (non-Laravel) that I wanted to try it on. When running, I get a ton of autoloader errors.

```
$ php ~/.config/composer/vendor/bin/phpinsights
PHP Warning:  include_once(vendor/squizlabs/php_codesniffer/autoload.php): failed to open stream: No such file or directory in /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Kernel.php on line 22
PHP Stack trace:
PHP   1. {main}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:0
PHP   2. {closure:/home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:10-37}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:37
PHP   3. NunoMaduro\PhpInsights\Domain\Kernel::bootstrap() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:18
PHP Warning:  include_once(): Failed opening 'vendor/squizlabs/php_codesniffer/autoload.php' for inclusion (include_path='.:/usr/share/php') in /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Kernel.php on line 22
PHP Stack trace:
PHP   1. {main}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:0
PHP   2. {closure:/home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:10-37}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:37
PHP   3. NunoMaduro\PhpInsights\Domain\Kernel::bootstrap() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:18
PHP Notice:  Uninitialized string offset: 1 in /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Analyser.php on line 314
PHP Stack trace:
PHP   1. {main}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:0
PHP   2. {closure:/home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:10-37}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:37
PHP   3. Symfony\Component\Console\Application->run() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:36
PHP   4. Symfony\Component\Console\Application->doRun() /home/francis/.config/composer/vendor/symfony/console/Application.php:145
PHP   5. Symfony\Component\Console\Application->doRunCommand() /home/francis/.config/composer/vendor/symfony/console/Application.php:269
PHP   6. NunoMaduro\PhpInsights\Application\Console\Commands\InvokableCommand->run() /home/francis/.config/composer/vendor/symfony/console/Application.php:908
PHP   7. NunoMaduro\PhpInsights\Application\Console\Commands\InvokableCommand->execute() /home/francis/.config/composer/vendor/symfony/console/Command/Command.php:255
PHP   8. call_user_func:{/home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39
PHP   9. NunoMaduro\PhpInsights\Application\Console\Commands\AnalyseCommand->__invoke() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39
PHP  10. NunoMaduro\PhpInsights\Application\Console\Analyser->analyse() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/AnalyseCommand.php:68
PHP  11. NunoMaduro\PhpInsights\Domain\Insights\InsightCollectionFactory->get() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Analyser.php:43
PHP  12. NunoMaduro\PhpInsights\Domain\Analyser->analyse() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Insights/InsightCollectionFactory.php:58
PHP  13. NunoMaduro\PhpInsights\Domain\Analyser->analyseFile() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Analyser.php:55
PHP Notice:  Uninitialized string offset: 1 in /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Analyser.php on line 315
PHP Stack trace:
PHP   1. {main}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:0
PHP   2. {closure:/home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:10-37}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:37
PHP   3. Symfony\Component\Console\Application->run() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:36
PHP   4. Symfony\Component\Console\Application->doRun() /home/francis/.config/composer/vendor/symfony/console/Application.php:145
PHP   5. Symfony\Component\Console\Application->doRunCommand() /home/francis/.config/composer/vendor/symfony/console/Application.php:269
PHP   6. NunoMaduro\PhpInsights\Application\Console\Commands\InvokableCommand->run() /home/francis/.config/composer/vendor/symfony/console/Application.php:908
PHP   7. NunoMaduro\PhpInsights\Application\Console\Commands\InvokableCommand->execute() /home/francis/.config/composer/vendor/symfony/console/Command/Command.php:255
PHP   8. call_user_func:{/home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39
PHP   9. NunoMaduro\PhpInsights\Application\Console\Commands\AnalyseCommand->__invoke() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39
PHP  10. NunoMaduro\PhpInsights\Application\Console\Analyser->analyse() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/AnalyseCommand.php:68
PHP  11. NunoMaduro\PhpInsights\Domain\Insights\InsightCollectionFactory->get() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Analyser.php:43
PHP  12. NunoMaduro\PhpInsights\Domain\Analyser->analyse() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Insights/InsightCollectionFactory.php:58
PHP  13. NunoMaduro\PhpInsights\Domain\Analyser->analyseFile() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Analyser.php:55
PHP Notice:  Uninitialized string offset: 1 in /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Analyser.php on line 314
PHP Stack trace:
PHP   1. {main}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:0
PHP   2. {closure:/home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:10-37}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:37
PHP   3. Symfony\Component\Console\Application->run() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:36
PHP   4. Symfony\Component\Console\Application->doRun() /home/francis/.config/composer/vendor/symfony/console/Application.php:145
PHP   5. Symfony\Component\Console\Application->doRunCommand() /home/francis/.config/composer/vendor/symfony/console/Application.php:269
PHP   6. NunoMaduro\PhpInsights\Application\Console\Commands\InvokableCommand->run() /home/francis/.config/composer/vendor/symfony/console/Application.php:908
PHP   7. NunoMaduro\PhpInsights\Application\Console\Commands\InvokableCommand->execute() /home/francis/.config/composer/vendor/symfony/console/Command/Command.php:255
PHP   8. call_user_func:{/home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39
PHP   9. NunoMaduro\PhpInsights\Application\Console\Commands\AnalyseCommand->__invoke() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39
PHP  10. NunoMaduro\PhpInsights\Application\Console\Analyser->analyse() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/AnalyseCommand.php:68
PHP  11. NunoMaduro\PhpInsights\Domain\Insights\InsightCollectionFactory->get() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Analyser.php:43
PHP  12. NunoMaduro\PhpInsights\Domain\Analyser->analyse() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Insights/InsightCollectionFactory.php:58
PHP  13. NunoMaduro\PhpInsights\Domain\Analyser->analyseFile() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Analyser.php:55
PHP Notice:  Uninitialized string offset: 1 in /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Analyser.php on line 315
PHP Stack trace:
PHP   1. {main}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:0
PHP   2. {closure:/home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:10-37}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:37
PHP   3. Symfony\Component\Console\Application->run() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:36
PHP   4. Symfony\Component\Console\Application->doRun() /home/francis/.config/composer/vendor/symfony/console/Application.php:145
PHP   5. Symfony\Component\Console\Application->doRunCommand() /home/francis/.config/composer/vendor/symfony/console/Application.php:269
PHP   6. NunoMaduro\PhpInsights\Application\Console\Commands\InvokableCommand->run() /home/francis/.config/composer/vendor/symfony/console/Application.php:908
PHP   7. NunoMaduro\PhpInsights\Application\Console\Commands\InvokableCommand->execute() /home/francis/.config/composer/vendor/symfony/console/Command/Command.php:255
PHP   8. call_user_func:{/home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39
PHP   9. NunoMaduro\PhpInsights\Application\Console\Commands\AnalyseCommand->__invoke() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39
PHP  10. NunoMaduro\PhpInsights\Application\Console\Analyser->analyse() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/AnalyseCommand.php:68
PHP  11. NunoMaduro\PhpInsights\Domain\Insights\InsightCollectionFactory->get() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Analyser.php:43
PHP  12. NunoMaduro\PhpInsights\Domain\Analyser->analyse() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Insights/InsightCollectionFactory.php:58
PHP  13. NunoMaduro\PhpInsights\Domain\Analyser->analyseFile() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Analyser.php:55
PHP Notice:  Uninitialized string offset: 1 in /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Analyser.php on line 314
PHP Stack trace:
PHP   1. {main}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:0
PHP   2. {closure:/home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:10-37}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:37
PHP   3. Symfony\Component\Console\Application->run() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:36
PHP   4. Symfony\Component\Console\Application->doRun() /home/francis/.config/composer/vendor/symfony/console/Application.php:145
PHP   5. Symfony\Component\Console\Application->doRunCommand() /home/francis/.config/composer/vendor/symfony/console/Application.php:269
PHP   6. NunoMaduro\PhpInsights\Application\Console\Commands\InvokableCommand->run() /home/francis/.config/composer/vendor/symfony/console/Application.php:908
PHP   7. NunoMaduro\PhpInsights\Application\Console\Commands\InvokableCommand->execute() /home/francis/.config/composer/vendor/symfony/console/Command/Command.php:255
PHP   8. call_user_func:{/home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39
PHP   9. NunoMaduro\PhpInsights\Application\Console\Commands\AnalyseCommand->__invoke() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39
PHP  10. NunoMaduro\PhpInsights\Application\Console\Analyser->analyse() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/AnalyseCommand.php:68
PHP  11. NunoMaduro\PhpInsights\Domain\Insights\InsightCollectionFactory->get() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Analyser.php:43
PHP  12. NunoMaduro\PhpInsights\Domain\Analyser->analyse() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Insights/InsightCollectionFactory.php:58
PHP  13. NunoMaduro\PhpInsights\Domain\Analyser->analyseFile() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Analyser.php:55
PHP Notice:  Uninitialized string offset: 1 in /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Analyser.php on line 315
PHP Stack trace:
PHP   1. {main}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:0
PHP   2. {closure:/home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:10-37}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:37
PHP   3. Symfony\Component\Console\Application->run() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:36
PHP   4. Symfony\Component\Console\Application->doRun() /home/francis/.config/composer/vendor/symfony/console/Application.php:145
PHP   5. Symfony\Component\Console\Application->doRunCommand() /home/francis/.config/composer/vendor/symfony/console/Application.php:269
PHP   6. NunoMaduro\PhpInsights\Application\Console\Commands\InvokableCommand->run() /home/francis/.config/composer/vendor/symfony/console/Application.php:908
PHP   7. NunoMaduro\PhpInsights\Application\Console\Commands\InvokableCommand->execute() /home/francis/.config/composer/vendor/symfony/console/Command/Command.php:255
PHP   8. call_user_func:{/home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39
PHP   9. NunoMaduro\PhpInsights\Application\Console\Commands\AnalyseCommand->__invoke() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39
PHP  10. NunoMaduro\PhpInsights\Application\Console\Analyser->analyse() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/AnalyseCommand.php:68
PHP  11. NunoMaduro\PhpInsights\Domain\Insights\InsightCollectionFactory->get() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Analyser.php:43
PHP  12. NunoMaduro\PhpInsights\Domain\Analyser->analyse() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Insights/InsightCollectionFactory.php:58
PHP  13. NunoMaduro\PhpInsights\Domain\Analyser->analyseFile() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Analyser.php:55
PHP Notice:  Uninitialized string offset: 1 in /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Analyser.php on line 314
PHP Stack trace:
PHP   1. {main}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:0
PHP   2. {closure:/home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:10-37}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:37
PHP   3. Symfony\Component\Console\Application->run() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:36
PHP   4. Symfony\Component\Console\Application->doRun() /home/francis/.config/composer/vendor/symfony/console/Application.php:145
PHP   5. Symfony\Component\Console\Application->doRunCommand() /home/francis/.config/composer/vendor/symfony/console/Application.php:269
PHP   6. NunoMaduro\PhpInsights\Application\Console\Commands\InvokableCommand->run() /home/francis/.config/composer/vendor/symfony/console/Application.php:908
PHP   7. NunoMaduro\PhpInsights\Application\Console\Commands\InvokableCommand->execute() /home/francis/.config/composer/vendor/symfony/console/Command/Command.php:255
PHP   8. call_user_func:{/home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39
PHP   9. NunoMaduro\PhpInsights\Application\Console\Commands\AnalyseCommand->__invoke() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39
PHP  10. NunoMaduro\PhpInsights\Application\Console\Analyser->analyse() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/AnalyseCommand.php:68
PHP  11. NunoMaduro\PhpInsights\Domain\Insights\InsightCollectionFactory->get() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Analyser.php:43
PHP  12. NunoMaduro\PhpInsights\Domain\Analyser->analyse() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Insights/InsightCollectionFactory.php:58
PHP  13. NunoMaduro\PhpInsights\Domain\Analyser->analyseFile() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Analyser.php:55
PHP Notice:  Uninitialized string offset: 1 in /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Analyser.php on line 315
PHP Stack trace:
PHP   1. {main}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:0
PHP   2. {closure:/home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:10-37}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:37
PHP   3. Symfony\Component\Console\Application->run() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:36
PHP   4. Symfony\Component\Console\Application->doRun() /home/francis/.config/composer/vendor/symfony/console/Application.php:145
PHP   5. Symfony\Component\Console\Application->doRunCommand() /home/francis/.config/composer/vendor/symfony/console/Application.php:269
PHP   6. NunoMaduro\PhpInsights\Application\Console\Commands\InvokableCommand->run() /home/francis/.config/composer/vendor/symfony/console/Application.php:908
PHP   7. NunoMaduro\PhpInsights\Application\Console\Commands\InvokableCommand->execute() /home/francis/.config/composer/vendor/symfony/console/Command/Command.php:255
PHP   8. call_user_func:{/home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39
PHP   9. NunoMaduro\PhpInsights\Application\Console\Commands\AnalyseCommand->__invoke() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39
PHP  10. NunoMaduro\PhpInsights\Application\Console\Analyser->analyse() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/AnalyseCommand.php:68
PHP  11. NunoMaduro\PhpInsights\Domain\Insights\InsightCollectionFactory->get() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Analyser.php:43
PHP  12. NunoMaduro\PhpInsights\Domain\Analyser->analyse() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Insights/InsightCollectionFactory.php:58
PHP  13. NunoMaduro\PhpInsights\Domain\Analyser->analyseFile() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Analyser.php:55
PHP Notice:  Uninitialized string offset: 1 in /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Analyser.php on line 314
PHP Stack trace:
PHP   1. {main}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:0
PHP   2. {closure:/home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:10-37}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:37
PHP   3. Symfony\Component\Console\Application->run() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:36
PHP   4. Symfony\Component\Console\Application->doRun() /home/francis/.config/composer/vendor/symfony/console/Application.php:145
PHP   5. Symfony\Component\Console\Application->doRunCommand() /home/francis/.config/composer/vendor/symfony/console/Application.php:269
PHP   6. NunoMaduro\PhpInsights\Application\Console\Commands\InvokableCommand->run() /home/francis/.config/composer/vendor/symfony/console/Application.php:908
PHP   7. NunoMaduro\PhpInsights\Application\Console\Commands\InvokableCommand->execute() /home/francis/.config/composer/vendor/symfony/console/Command/Command.php:255
PHP   8. call_user_func:{/home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39
PHP   9. NunoMaduro\PhpInsights\Application\Console\Commands\AnalyseCommand->__invoke() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39
PHP  10. NunoMaduro\PhpInsights\Application\Console\Analyser->analyse() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/AnalyseCommand.php:68
PHP  11. NunoMaduro\PhpInsights\Domain\Insights\InsightCollectionFactory->get() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Analyser.php:43
PHP  12. NunoMaduro\PhpInsights\Domain\Analyser->analyse() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Insights/InsightCollectionFactory.php:58
PHP  13. NunoMaduro\PhpInsights\Domain\Analyser->analyseFile() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Analyser.php:55
PHP Notice:  Uninitialized string offset: 1 in /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Analyser.php on line 315
PHP Stack trace:
PHP   1. {main}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:0
PHP   2. {closure:/home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:10-37}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:37
PHP   3. Symfony\Component\Console\Application->run() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:36
PHP   4. Symfony\Component\Console\Application->doRun() /home/francis/.config/composer/vendor/symfony/console/Application.php:145
PHP   5. Symfony\Component\Console\Application->doRunCommand() /home/francis/.config/composer/vendor/symfony/console/Application.php:269
PHP   6. NunoMaduro\PhpInsights\Application\Console\Commands\InvokableCommand->run() /home/francis/.config/composer/vendor/symfony/console/Application.php:908
PHP   7. NunoMaduro\PhpInsights\Application\Console\Commands\InvokableCommand->execute() /home/francis/.config/composer/vendor/symfony/console/Command/Command.php:255
PHP   8. call_user_func:{/home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39
PHP   9. NunoMaduro\PhpInsights\Application\Console\Commands\AnalyseCommand->__invoke() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39
PHP  10. NunoMaduro\PhpInsights\Application\Console\Analyser->analyse() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/AnalyseCommand.php:68
PHP  11. NunoMaduro\PhpInsights\Domain\Insights\InsightCollectionFactory->get() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Analyser.php:43
PHP  12. NunoMaduro\PhpInsights\Domain\Analyser->analyse() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Insights/InsightCollectionFactory.php:58
PHP  13. NunoMaduro\PhpInsights\Domain\Analyser->analyseFile() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Analyser.php:55
PHP Fatal error:  Interface 'PHP_CodeSniffer\Sniffs\Sniff' not found in /home/francis/.config/composer/vendor/object-calisthenics/phpcs-calisthenics-rules/src/ObjectCalisthenics/Sniffs/Classes/ForbiddenPublicPropertySniff.php on line 11
PHP Stack trace:
PHP   1. {main}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:0
PHP   2. {closure:/home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:10-37}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:37
PHP   3. Symfony\Component\Console\Application->run() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:36
PHP   4. Symfony\Component\Console\Application->doRun() /home/francis/.config/composer/vendor/symfony/console/Application.php:145
PHP   5. Symfony\Component\Console\Application->doRunCommand() /home/francis/.config/composer/vendor/symfony/console/Application.php:269
PHP   6. NunoMaduro\PhpInsights\Application\Console\Commands\InvokableCommand->run() /home/francis/.config/composer/vendor/symfony/console/Application.php:908
PHP   7. NunoMaduro\PhpInsights\Application\Console\Commands\InvokableCommand->execute() /home/francis/.config/composer/vendor/symfony/console/Command/Command.php:255
PHP   8. call_user_func:{/home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39
PHP   9. NunoMaduro\PhpInsights\Application\Console\Commands\AnalyseCommand->__invoke() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39
PHP  10. NunoMaduro\PhpInsights\Application\Console\Analyser->analyse() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/AnalyseCommand.php:68
PHP  11. NunoMaduro\PhpInsights\Domain\Insights\InsightCollectionFactory->get() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Analyser.php:43
PHP  12. array_map() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Insights/InsightCollectionFactory.php:79
PHP  13. NunoMaduro\PhpInsights\Domain\Insights\InsightCollectionFactory::NunoMaduro\PhpInsights\Domain\Insights\{closure}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Insights/InsightCollectionFactory.php:79
PHP  14. class_implements() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Insights/InsightCollectionFactory.php:70
PHP  15. spl_autoload_call() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Insights/InsightCollectionFactory.php:70
PHP  16. Composer\Autoload\ClassLoader->loadClass() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Insights/InsightCollectionFactory.php:70
PHP  17. Composer\Autoload\includeFile() /home/francis/.config/composer/vendor/composer/ClassLoader.php:322
PHP  18. include() /home/francis/.config/composer/vendor/composer/ClassLoader.php:444
```

**Comment by szepeviktor** [comment]
That is why modern tools suggest phar distribution.

**Comment by nunomaduro** [comment]
@szepeviktor Exactly, we need to work on that.

Meanwhile this is fixed. https://github.com/nunomaduro/phpinsights/commit/e18777c76e8fe2de262894043a58ae43f5ee286a

Please perform `composer global update nunomaduro/phpinsights`.

**Comment by francislavoie** [comment]
Thanks!

It does run now, but I still get lots of notices, then later after running for 4% of the way, it dies again:

```
PHP Notice:  Uninitialized string offset: 1 in /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Analyser.php on line 314
PHP Stack trace:
PHP   1. {main}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:0
PHP   2. {closure:/home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:10-37}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:37
PHP   3. Symfony\Component\Console\Application->run() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:36
PHP   4. Symfony\Component\Console\Application->doRun() /home/francis/.config/composer/vendor/symfony/console/Application.php:145
PHP   5. Symfony\Component\Console\Application->doRunCommand() /home/francis/.config/composer/vendor/symfony/console/Application.php:269
PHP   6. NunoMaduro\PhpInsights\Application\Console\Commands\InvokableCommand->run() /home/francis/.config/composer/vendor/symfony/console/Application.php:908
PHP   7. NunoMaduro\PhpInsights\Application\Console\Commands\InvokableCommand->execute() /home/francis/.config/composer/vendor/symfony/console/Command/Command.php:255
PHP   8. call_user_func:{/home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39
PHP   9. NunoMaduro\PhpInsights\Application\Console\Commands\AnalyseCommand->__invoke() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39
PHP  10. NunoMaduro\PhpInsights\Application\Console\Analyser->analyse() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/AnalyseCommand.php:68
PHP  11. NunoMaduro\PhpInsights\Domain\Insights\InsightCollectionFactory->get() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Analyser.php:43
PHP  12. NunoMaduro\PhpInsights\Domain\Analyser->analyse() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Insights/InsightCollectionFactory.php:58
PHP  13. NunoMaduro\PhpInsights\Domain\Analyser->analyseFile() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Analyser.php:55
PHP Notice:  Uninitialized string offset: 1 in /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Analyser.php on line 315
PHP Stack trace:
PHP   1. {main}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:0
PHP   2. {closure:/home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:10-37}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:37
PHP   3. Symfony\Component\Console\Application->run() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:36
PHP   4. Symfony\Component\Console\Application->doRun() /home/francis/.config/composer/vendor/symfony/console/Application.php:145
PHP   5. Symfony\Component\Console\Application->doRunCommand() /home/francis/.config/composer/vendor/symfony/console/Application.php:269
PHP   6. NunoMaduro\PhpInsights\Application\Console\Commands\InvokableCommand->run() /home/francis/.config/composer/vendor/symfony/console/Application.php:908
PHP   7. NunoMaduro\PhpInsights\Application\Console\Commands\InvokableCommand->execute() /home/francis/.config/composer/vendor/symfony/console/Command/Command.php:255
PHP   8. call_user_func:{/home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39
PHP   9. NunoMaduro\PhpInsights\Application\Console\Commands\AnalyseCommand->__invoke() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39
PHP  10. NunoMaduro\PhpInsights\Application\Console\Analyser->analyse() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/AnalyseCommand.php:68
PHP  11. NunoMaduro\PhpInsights\Domain\Insights\InsightCollectionFactory->get() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Analyser.php:43
PHP  12. NunoMaduro\PhpInsights\Domain\Analyser->analyse() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Insights/InsightCollectionFactory.php:58
PHP  13. NunoMaduro\PhpInsights\Domain\Analyser->analyseFile() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Analyser.php:55
PHP Notice:  Uninitialized string offset: 1 in /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Analyser.php on line 314
PHP Stack trace:
PHP   1. {main}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:0
PHP   2. {closure:/home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:10-37}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:37
PHP   3. Symfony\Component\Console\Application->run() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:36
PHP   4. Symfony\Component\Console\Application->doRun() /home/francis/.config/composer/vendor/symfony/console/Application.php:145
PHP   5. Symfony\Component\Console\Application->doRunCommand() /home/francis/.config/composer/vendor/symfony/console/Application.php:269
PHP   6. NunoMaduro\PhpInsights\Application\Console\Commands\InvokableCommand->run() /home/francis/.config/composer/vendor/symfony/console/Application.php:908
PHP   7. NunoMaduro\PhpInsights\Application\Console\Commands\InvokableCommand->execute() /home/francis/.config/composer/vendor/symfony/console/Command/Command.php:255
PHP   8. call_user_func:{/home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39
PHP   9. NunoMaduro\PhpInsights\Application\Console\Commands\AnalyseCommand->__invoke() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39
PHP  10. NunoMaduro\PhpInsights\Application\Console\Analyser->analyse() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/AnalyseCommand.php:68
PHP  11. NunoMaduro\PhpInsights\Domain\Insights\InsightCollectionFactory->get() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Analyser.php:43
PHP  12. NunoMaduro\PhpInsights\Domain\Analyser->analyse() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Insights/InsightCollectionFactory.php:58
PHP  13. NunoMaduro\PhpInsights\Domain\Analyser->analyseFile() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Analyser.php:55
PHP Notice:  Uninitialized string offset: 1 in /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Analyser.php on line 315
PHP Stack trace:
PHP   1. {main}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:0
PHP   2. {closure:/home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:10-37}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:37
PHP   3. Symfony\Component\Console\Application->run() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:36
PHP   4. Symfony\Component\Console\Application->doRun() /home/francis/.config/composer/vendor/symfony/console/Application.php:145
PHP   5. Symfony\Component\Console\Application->doRunCommand() /home/francis/.config/composer/vendor/symfony/console/Application.php:269
PHP   6. NunoMaduro\PhpInsights\Application\Console\Commands\InvokableCommand->run() /home/francis/.config/composer/vendor/symfony/console/Application.php:908
PHP   7. NunoMaduro\PhpInsights\Application\Console\Commands\InvokableCommand->execute() /home/francis/.config/composer/vendor/symfony/console/Command/Command.php:255
PHP   8. call_user_func:{/home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39
PHP   9. NunoMaduro\PhpInsights\Application\Console\Commands\AnalyseCommand->__invoke() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39
PHP  10. NunoMaduro\PhpInsights\Application\Console\Analyser->analyse() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/AnalyseCommand.php:68
PHP  11. NunoMaduro\PhpInsights\Domain\Insights\InsightCollectionFactory->get() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Analyser.php:43
PHP  12. NunoMaduro\PhpInsights\Domain\Analyser->analyse() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Insights/InsightCollectionFactory.php:58
PHP  13. NunoMaduro\PhpInsights\Domain\Analyser->analyseFile() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Analyser.php:55
PHP Notice:  Uninitialized string offset: 1 in /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Analyser.php on line 314
PHP Stack trace:
PHP   1. {main}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:0
PHP   2. {closure:/home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:10-37}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:37
PHP   3. Symfony\Component\Console\Application->run() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:36
PHP   4. Symfony\Component\Console\Application->doRun() /home/francis/.config/composer/vendor/symfony/console/Application.php:145
PHP   5. Symfony\Component\Console\Application->doRunCommand() /home/francis/.config/composer/vendor/symfony/console/Application.php:269
PHP   6. NunoMaduro\PhpInsights\Application\Console\Commands\InvokableCommand->run() /home/francis/.config/composer/vendor/symfony/console/Application.php:908
PHP   7. NunoMaduro\PhpInsights\Application\Console\Commands\InvokableCommand->execute() /home/francis/.config/composer/vendor/symfony/console/Command/Command.php:255
PHP   8. call_user_func:{/home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39
PHP   9. NunoMaduro\PhpInsights\Application\Console\Commands\AnalyseCommand->__invoke() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39
PHP  10. NunoMaduro\PhpInsights\Application\Console\Analyser->analyse() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/AnalyseCommand.php:68
PHP  11. NunoMaduro\PhpInsights\Domain\Insights\InsightCollectionFactory->get() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Analyser.php:43
PHP  12. NunoMaduro\PhpInsights\Domain\Analyser->analyse() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Insights/InsightCollectionFactory.php:58
PHP  13. NunoMaduro\PhpInsights\Domain\Analyser->analyseFile() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Analyser.php:55
PHP Notice:  Uninitialized string offset: 1 in /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Analyser.php on line 315
PHP Stack trace:
PHP   1. {main}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:0
PHP   2. {closure:/home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:10-37}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:37
PHP   3. Symfony\Component\Console\Application->run() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:36
PHP   4. Symfony\Component\Console\Application->doRun() /home/francis/.config/composer/vendor/symfony/console/Application.php:145
PHP   5. Symfony\Component\Console\Application->doRunCommand() /home/francis/.config/composer/vendor/symfony/console/Application.php:269
PHP   6. NunoMaduro\PhpInsights\Application\Console\Commands\InvokableCommand->run() /home/francis/.config/composer/vendor/symfony/console/Application.php:908
PHP   7. NunoMaduro\PhpInsights\Application\Console\Commands\InvokableCommand->execute() /home/francis/.config/composer/vendor/symfony/console/Command/Command.php:255
PHP   8. call_user_func:{/home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39
PHP   9. NunoMaduro\PhpInsights\Application\Console\Commands\AnalyseCommand->__invoke() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39
PHP  10. NunoMaduro\PhpInsights\Application\Console\Analyser->analyse() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/AnalyseCommand.php:68
PHP  11. NunoMaduro\PhpInsights\Domain\Insights\InsightCollectionFactory->get() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Analyser.php:43
PHP  12. NunoMaduro\PhpInsights\Domain\Analyser->analyse() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Insights/InsightCollectionFactory.php:58
PHP  13. NunoMaduro\PhpInsights\Domain\Analyser->analyseFile() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Analyser.php:55
PHP Notice:  Uninitialized string offset: 1 in /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Analyser.php on line 314
PHP Stack trace:
PHP   1. {main}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:0
PHP   2. {closure:/home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:10-37}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:37
PHP   3. Symfony\Component\Console\Application->run() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:36
PHP   4. Symfony\Component\Console\Application->doRun() /home/francis/.config/composer/vendor/symfony/console/Application.php:145
PHP   5. Symfony\Component\Console\Application->doRunCommand() /home/francis/.config/composer/vendor/symfony/console/Application.php:269
PHP   6. NunoMaduro\PhpInsights\Application\Console\Commands\InvokableCommand->run() /home/francis/.config/composer/vendor/symfony/console/Application.php:908
PHP   7. NunoMaduro\PhpInsights\Application\Console\Commands\InvokableCommand->execute() /home/francis/.config/composer/vendor/symfony/console/Command/Command.php:255
PHP   8. call_user_func:{/home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39
PHP   9. NunoMaduro\PhpInsights\Application\Console\Commands\AnalyseCommand->__invoke() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39
PHP  10. NunoMaduro\PhpInsights\Application\Console\Analyser->analyse() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/AnalyseCommand.php:68
PHP  11. NunoMaduro\PhpInsights\Domain\Insights\InsightCollectionFactory->get() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Analyser.php:43
PHP  12. NunoMaduro\PhpInsights\Domain\Analyser->analyse() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Insights/InsightCollectionFactory.php:58
PHP  13. NunoMaduro\PhpInsights\Domain\Analyser->analyseFile() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Analyser.php:55
PHP Notice:  Uninitialized string offset: 1 in /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Analyser.php on line 315
PHP Stack trace:
PHP   1. {main}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:0
PHP   2. {closure:/home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:10-37}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:37
PHP   3. Symfony\Component\Console\Application->run() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:36
PHP   4. Symfony\Component\Console\Application->doRun() /home/francis/.config/composer/vendor/symfony/console/Application.php:145
PHP   5. Symfony\Component\Console\Application->doRunCommand() /home/francis/.config/composer/vendor/symfony/console/Application.php:269
PHP   6. NunoMaduro\PhpInsights\Application\Console\Commands\InvokableCommand->run() /home/francis/.config/composer/vendor/symfony/console/Application.php:908
PHP   7. NunoMaduro\PhpInsights\Application\Console\Commands\InvokableCommand->execute() /home/francis/.config/composer/vendor/symfony/console/Command/Command.php:255
PHP   8. call_user_func:{/home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39
PHP   9. NunoMaduro\PhpInsights\Application\Console\Commands\AnalyseCommand->__invoke() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39
PHP  10. NunoMaduro\PhpInsights\Application\Console\Analyser->analyse() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/AnalyseCommand.php:68
PHP  11. NunoMaduro\PhpInsights\Domain\Insights\InsightCollectionFactory->get() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Analyser.php:43
PHP  12. NunoMaduro\PhpInsights\Domain\Analyser->analyse() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Insights/InsightCollectionFactory.php:58
PHP  13. NunoMaduro\PhpInsights\Domain\Analyser->analyseFile() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Analyser.php:55
PHP Notice:  Uninitialized string offset: 1 in /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Analyser.php on line 314
PHP Stack trace:
PHP   1. {main}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:0
PHP   2. {closure:/home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:10-37}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:37
PHP   3. Symfony\Component\Console\Application->run() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:36
PHP   4. Symfony\Component\Console\Application->doRun() /home/francis/.config/composer/vendor/symfony/console/Application.php:145
PHP   5. Symfony\Component\Console\Application->doRunCommand() /home/francis/.config/composer/vendor/symfony/console/Application.php:269
PHP   6. NunoMaduro\PhpInsights\Application\Console\Commands\InvokableCommand->run() /home/francis/.config/composer/vendor/symfony/console/Application.php:908
PHP   7. NunoMaduro\PhpInsights\Application\Console\Commands\InvokableCommand->execute() /home/francis/.config/composer/vendor/symfony/console/Command/Command.php:255
PHP   8. call_user_func:{/home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39
PHP   9. NunoMaduro\PhpInsights\Application\Console\Commands\AnalyseCommand->__invoke() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39
PHP  10. NunoMaduro\PhpInsights\Application\Console\Analyser->analyse() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/AnalyseCommand.php:68
PHP  11. NunoMaduro\PhpInsights\Domain\Insights\InsightCollectionFactory->get() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Analyser.php:43
PHP  12. NunoMaduro\PhpInsights\Domain\Analyser->analyse() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Insights/InsightCollectionFactory.php:58
PHP  13. NunoMaduro\PhpInsights\Domain\Analyser->analyseFile() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Analyser.php:55
PHP Notice:  Uninitialized string offset: 1 in /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Analyser.php on line 315
PHP Stack trace:
PHP   1. {main}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:0
PHP   2. {closure:/home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:10-37}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:37
PHP   3. Symfony\Component\Console\Application->run() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:36
PHP   4. Symfony\Component\Console\Application->doRun() /home/francis/.config/composer/vendor/symfony/console/Application.php:145
PHP   5. Symfony\Component\Console\Application->doRunCommand() /home/francis/.config/composer/vendor/symfony/console/Application.php:269
PHP   6. NunoMaduro\PhpInsights\Application\Console\Commands\InvokableCommand->run() /home/francis/.config/composer/vendor/symfony/console/Application.php:908
PHP   7. NunoMaduro\PhpInsights\Application\Console\Commands\InvokableCommand->execute() /home/francis/.config/composer/vendor/symfony/console/Command/Command.php:255
PHP   8. call_user_func:{/home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39
PHP   9. NunoMaduro\PhpInsights\Application\Console\Commands\AnalyseCommand->__invoke() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39
PHP  10. NunoMaduro\PhpInsights\Application\Console\Analyser->analyse() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/AnalyseCommand.php:68
PHP  11. NunoMaduro\PhpInsights\Domain\Insights\InsightCollectionFactory->get() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Analyser.php:43
PHP  12. NunoMaduro\PhpInsights\Domain\Analyser->analyse() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Insights/InsightCollectionFactory.php:58
PHP  13. NunoMaduro\PhpInsights\Domain\Analyser->analyseFile() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Analyser.php:55
  179/4092 [▓░░░░░░░░░░░░░░░░░░░░░░░░░░░]   4%PHP Notice:  Undefined offset: 0 in /home/francis/.config/composer/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/UseStatementHelper.php on line 147
PHP Stack trace:
PHP   1. {main}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:0
PHP   2. {closure:/home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:10-37}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:37
PHP   3. Symfony\Component\Console\Application->run() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/bin/phpinsights:36
PHP   4. Symfony\Component\Console\Application->doRun() /home/francis/.config/composer/vendor/symfony/console/Application.php:145
PHP   5. Symfony\Component\Console\Application->doRunCommand() /home/francis/.config/composer/vendor/symfony/console/Application.php:269
PHP   6. NunoMaduro\PhpInsights\Application\Console\Commands\InvokableCommand->run() /home/francis/.config/composer/vendor/symfony/console/Application.php:908
PHP   7. NunoMaduro\PhpInsights\Application\Console\Commands\InvokableCommand->execute() /home/francis/.config/composer/vendor/symfony/console/Command/Command.php:255
PHP   8. call_user_func:{/home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39
PHP   9. NunoMaduro\PhpInsights\Application\Console\Commands\AnalyseCommand->__invoke() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39
PHP  10. NunoMaduro\PhpInsights\Application\Console\Analyser->analyse() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/AnalyseCommand.php:68
PHP  11. NunoMaduro\PhpInsights\Domain\Insights\InsightCollectionFactory->get() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Application/Console/Analyser.php:43
PHP  12. array_map() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Insights/InsightCollectionFactory.php:79
PHP  13. NunoMaduro\PhpInsights\Domain\Insights\InsightCollectionFactory::NunoMaduro\PhpInsights\Domain\Insights\{closure}() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Insights/InsightCollectionFactory.php:79
PHP  14. NunoMaduro\PhpInsights\Domain\Insights\InsightFactory->makeFrom() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Insights/InsightCollectionFactory.php:74
PHP  15. NunoMaduro\PhpInsights\Domain\Insights\InsightFactory->getSniffCollector() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Insights/InsightFactory.php:71
PHP  16. Symplify\EasyCodingStandard\Application\EasyCodingStandardApplication->run() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/Insights/InsightFactory.php:191
PHP  17. Symplify\EasyCodingStandard\Application\EasyCodingStandardApplication->processFoundFiles() /home/francis/.config/composer/vendor/symplify/easy-coding-standard/src/Application/EasyCodingStandardApplication.php:96
PHP  18. Symplify\EasyCodingStandard\Application\EasyCodingStandardApplication->processFileInfoWithCallable() /home/francis/.config/composer/vendor/symplify/easy-coding-standard/src/Application/EasyCodingStandardApplication.php:140
PHP  19. Symplify\EasyCodingStandard\Application\EasyCodingStandardApplication->Symplify\EasyCodingStandard\Application\{closure}() /home/francis/.config/composer/vendor/symplify/easy-coding-standard/src/Application/EasyCodingStandardApplication.php:166
PHP  20. Symplify\EasyCodingStandard\Application\SingleFileProcessor->processFileInfo() /home/francis/.config/composer/vendor/symplify/easy-coding-standard/src/Application/EasyCodingStandardApplication.php:139
PHP  21. NunoMaduro\PhpInsights\Domain\FileProcessor->processFile() /home/francis/.config/composer/vendor/symplify/easy-coding-standard/src/Application/SingleFileProcessor.php:63
PHP  22. NunoMaduro\PhpInsights\Domain\File->processWithTokenListenersAndFileInfo() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/FileProcessor.php:79
PHP  23. NunoMaduro\PhpInsights\Domain\File->process() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/File.php:171
PHP  24. SlevomatCodingStandard\Sniffs\PHP\OptimizedFunctionsWithoutUnpackingSniff->process() /home/francis/.config/composer/vendor/nunomaduro/phpinsights/src/Domain/File.php:128
PHP  25. SlevomatCodingStandard\Helpers\UseStatementHelper::getUseStatementsForPointer() /home/francis/.config/composer/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/PHP/OptimizedFunctionsWithoutUnpackingSniff.php:94
PHP  26. SlevomatCodingStandard\Helpers\UseStatementHelper::getFileUseStatements() /home/francis/.config/composer/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/UseStatementHelper.php:111
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to SlevomatCodingStandard\Helpers\UseStatementHelper::getUseStatementPointers() must be of the type integer, null given, called in /home/francis/.config/composer/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/UseStatementHelper.php on line 149 and defined in /home/francis/.config/composer/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/UseStatementHelper.php:193
Stack trace:
#0 /home/francis/.config/composer/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/UseStatementHelper.php(149): SlevomatCodingStandard\Helpers\UseStatementHelper::getUseStatementPointers(Object(NunoMaduro\PhpInsights\Domain\File), NULL)
#1 /home/francis/.config/composer/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/UseStatementHelper.php(111): SlevomatCodingStandard\Helpers\UseStatementHelper::getFileUseStatements(Object(NunoMaduro\PhpInsights\Domain\File))
#2 /home/francis/.config/composer/vendor/slevomat/coding-standard/SlevomatCodingStan in /home/francis/.config/composer/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/UseStatementHelper.php on line 193
```

**Comment by francislavoie** [comment]
I ran it on a Laravel project instead and it seems to work fine. I think it's just weird edgecases running on a crazy legacy project 🤪
