### ISSUE TITLE
version problem in composer for clean Laravel 9.

### ISSUE THREAD

**Issue by divoto** [nunomaduro/phpinsights#561]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| Library version  | x.y.z

On clean Laravel 9 i get error when using composer require:

`composer require nunomaduro/phpinsights --dev
Using version ^2.1 for nunomaduro/phpinsights
./composer.json has been updated
Running composer update nunomaduro/phpinsights
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires nunomaduro/phpinsights ^2.1 -> satisfiable by nunomaduro/phpinsights[v2.1.0].
    - nunomaduro/phpinsights v2.1.0 requires psr/simple-cache ^1.0 -> found psr/simple-cache[1.0.0, 1.0.1] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
`
Again problem with psr/simple-cache.

Thank you.

<!--
Love PHP Insights? Please consider supporting us via Patreon or OpenCollective:
👉  https://www.patreon.com/nunomaduro
👉  https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=66BYDWAT92N6L
--

**Comment by yoeriboven** [comment]
Yeah, I got the same on an upgraded installation instead of a clean one.

**Comment by 50bhan** [comment]
Yes, there is an issue with dependencies. But you can fix it with `composer require nunomaduro/phpinsights --dev --with-all-dependencies` until the fix.

**Comment by divoto** [comment]
Hi @50bhan . I have try it but without any success:
```
$ composer require nunomaduro/phpinsights --dev --with-all-dependencies
Using version ^2.1 for nunomaduro/phpinsights
./composer.json has been updated
Running composer update nunomaduro/phpinsights --with-all-dependencies
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - symfony/translation v6.0.3 requires symfony/translation-contracts ^2.3|^3.0 -> found symfony/translation-contracts[dev-main, v2.3.0, ..., 2.5.x-dev, v3.0.0, 3.0.x-dev, 3.1.x-dev (alias of dev-main)] but it conflicts with another require.
    - laravel/framework v9.0.2 requires nesbot/carbon ^2.53.1 -> satisfiable by nesbot/carbon[2.56.0].
    - nesbot/carbon 2.56.0 requires symfony/translation ^3.4 || ^4.0 || ^5.0 || ^6.0 -> satisfiable by symfony/translation[v6.0.3].
    - laravel/framework is locked to version v9.0.2 and an update of this package was not requested.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

**Comment by 50bhan** [comment]
@divoto It's odd! Because I was able to install the package on a clean L9.
<img width="1792" alt="Screen Shot 2022-02-15 at 12 17 21" src="https://user-images.githubusercontent.com/36772278/154025729-78467d75-72d2-4c14-921a-b47ddd235dae.png">

**Comment by divoto** [comment]
> @divoto It's odd! Because I was able to install the package on a clean L9.
> 
> <img alt="Screen Shot 2022-02-15 at 12 17 21" width="1792" src="https://user-images.githubusercontent.com/36772278/154025729-78467d75-72d2-4c14-921a-b47ddd235dae.png">

What version of PHP. Mine is 8.0

**Comment by divoto** [comment]
Hi @50bhan 
I had time today to debug te error. It appears that was in conflict with **psr/simple-cache** that i had updated to 3.0 while phpinsights requires 1.0.*
Thanks for the support.

**Comment by TAvsec** [comment]
Hi, I think that I have a connected issue. I managed to install phpinsights, but when I run `php artisan insights`, I get the following error:

```
❯ php artisan insights

 29/29 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 ✨ Analysis Completed !

[2022-02-22 12:15:58] `/Users/path/to/my/project`


   TypeError 

  Cannot assign Composer\PartialComposer to property NunoMaduro\PhpInsights\Domain\ComposerLoader::$composer of type ?Composer\Composer

  at vendor/nunomaduro/phpinsights/src/Domain/ComposerLoader.php:30
     26▕             self::$currentCollector = $collector;
     27▕ 
     28▕             $io = new NullIO();
     29▕             $composerPath = ComposerFinder::getPath($collector);
  ➜  30▕             self::$composer = (new Factory())->createComposer($io, ComposerFinder::getPath($collector), false, null, false);
     31▕             self::$composer->setLocker(self::getLocker($composerPath, $io));
     32▕         }
     33▕ 
     34▕         return self::$composer;

      +22 vendor frames 
  23  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```
This is my `composer.json` file:

```
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "require": {
        "php": "^8.0.2",
        "fruitcake/laravel-cors": "^2.0.5",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^9.0",
        "laravel/sanctum": "^2.14",
        "laravel/tinker": "^2.7",
        "psr/simple-cache": "1.0.*"
    },
    "require-dev": {
        "fakerphp/faker": "^1.9.1",
        "laravel/envoy": "^2.8",
        "laravel/sail": "^1.0.1",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^6.1",
        "nunomaduro/phpinsights": "^2.1",
        "php-parallel-lint/php-console-highlighter": "~0.3",
        "phpunit/phpunit": "^9.5.10",
        "spatie/laravel-ignition": "^1.0"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-update-cmd": [
            "@php artisan vendor:publish --tag=laravel-assets --ansi --force"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true,
        "allow-plugins": {
            "dealerdirect/phpcodesniffer-composer-installer": true
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

I tried deleting `vendor` and `composer.lock`, as well as running `composer update`, but that did not fix the problem. Any ideas how could I fix the issue?

**Comment by 50bhan** [comment]
@TAvsec Please follow this issue #565

**Comment by cmgmyr** [comment]
fixed in #566

**Comment by Sergiobop** [comment]
The problem is not solved @cmgmyr 

  Problem 1
    - Root composer.json requires nunomaduro/phpinsights ^2.2 -> satisfiable by nunomaduro/phpinsights[v2.2.0].
    - nunomaduro/phpinsights v2.2.0 requires psr/simple-cache ^1.0 -> found psr/simple-cache[1.0.0, 1.0.1] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
